name: nickel
channels:
  - defaults
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - matplotlib=3.6.3
  - numpy=1.23.5
  - jupyterlab
  - pip:
    - qiskit==0.44.1
    - qiskit[visualization]
    - qiskit-aer>=0.12.0,<0.13.0
    - qutip==4.7.3
    - cirq==1.2.0
    - ipykernel>=6.25.2